name: Update contract

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'
          java-package: jdk

      - name: Update Contract
        run: ./gradlew clean build publish --no-daemon -DpublishRegistryUsername=${{ github.actor }} -DpublishRegistryPassword=${{ secrets.GITHUB_TOKEN }}
